name: "[nightly]-[thud]-meta-clang"

on:
  schedule:
    - cron: "30 14 * * *"

jobs:
  qemux86:
    name: "qemux86 with meta-clang"
    env:
      DISTRO: scatest
      MACHINE: qemux86
      SCABRANCH: thud

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        with:
          ref: thud
      - name: Update APT
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get -yq --no-install-suggests --no-install-recommends install build-essential chrpath diffstat gawk gcc-multilib git-core libsdl1.2-dev python3 socat texinfo unzip wget xterm
      - name: Check out poky
        run: git clone git://git.yoctoproject.org/poky.git/ -b $SCABRANCH poky
      - name: Check out meta-clang
        run: git clone https://github.com/kraj/meta-clang.git -b $SCABRANCH meta-clang
      - name: Setup poky
        run: source poky/oe-init-build-env
      - name: add meta-sca
        run: source poky/oe-init-build-env && bitbake-layers add-layer $(pwd)/..
      - name: add meta-clang
        run: source poky/oe-init-build-env && bitbake-layers add-layer $(pwd)/../meta-clang
      - name: prepare local.conf
        run: source poky/oe-init-build-env && echo 'INHERIT +="rm_work"' >> conf/local.conf
      - name: local.conf+
        run: source poky/oe-init-build-env && echo 'PREFERRED_VERSION_clang-native = "8.%"' >> conf/local.conf
      - name: build
        run: source poky/oe-init-build-env && $(pwd)/../recipes-sca-test/test.sh
      # - name: test results
      #   run: source poky/oe-init-build-env && eval $(bitbake busybox -e | grep "^SCA_EXPORT_DIR") && $(pwd)/../scripts/check_results $SCA_EXPORT_DIR
